### ISSUE TITLE
Sample R-shiny app

### ISSUE THREAD

**Issue by samskhan** [samskhan/KSULasso#13]
Find and Try to clone an already made rshiny app and run on local computer.

**Comment by jamesmatthewhamilton** [comment]
I make these at work. Please set up a meeting with me if you have questions.

**Comment by Sm00veGhost** [comment]
![testsite](https://user-images.githubusercontent.com/46979948/53030075-2b40f100-3438-11e9-941b-695b91ddda51.PNG)
![progress](https://user-images.githubusercontent.com/46979948/53030076-2b40f100-3438-11e9-8a15-dc0cf3e77184.PNG)

Here is the progress I made on the website, I can only host locally from my desktop for now but I'll get a linux server running eventually. Had issues incorporating CSS with Django but I figured it out. The about us and services are still a work in progress as I haven't done much with it.

**Comment by Sm00veGhost** [comment]
![image](https://user-images.githubusercontent.com/46979948/53030339-9985b380-3438-11e9-9f83-b14318ec4a0e.png)

Don't worry about the pricing as it was just a part of the template
