### ISSUE TITLE
Research templates that are compatible with python/R backend.

### ISSUE THREAD

**Issue by samskhan** [samskhan/KSULasso#6]
Research website templates that incorporate python/r extensively.

**Comment by jamesmatthewhamilton** [comment]
If I am understanding this correctly, you are asking for a web template that demos R code. If so, RShiny is a powerful package used by websites like nytimes that are there own independent webpage – note the word page. I am sure Python has something similar if needed. The main website would simply need to link to the R/Python based webpage. This would appear seamless. The rest of the website can be completely separated from the R and Python. I can show you my R based web application using RShiny next meeting to see if that is what you are looking for. For the R/Python based webpages no HTML or Javascript knowledge is needed. Of course, for the rest of the website HTML knowledge is needed.

**Comment by samskhan** [comment]
https://medium.com/@plotlygraphs/introducing-dash-5ecf7191b503

This is probably a good equivalent to it, but Rshiny looks pretty good, @DannyChoo92 @Sm00veGhost , you guys might wanna play around or read up on both packages so when we discuss it with Matthew on Tuesday we have a general idea on how these work.

**Comment by Sm00veGhost** [comment]
[To_Do.docx](https://github.com/samskhan/KSULasso/files/2814437/To_Do.docx)

**Comment by JasonWein** [comment]
https://cran.r-project.org/web/packages/lars/lars.pdf
